image: node:16

stages:
  - build
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $DEV_HOST > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - unset CI
    - npm install --progress=false
    - npm run build
#    - NODE_ENV=production GENERATE_SOURCEMAP=false npm run build
    - scp -r -B build/* $TEST_USER@$TEST_HOST:/var/www/hr/
  only:
    - test
